version: '3.8'
services:
  proxy:
    build: ./src
    ports:
      - "12345:12345"
    restart: always
    tty: true         # Allocate a pseudo-TTY
    stdin_open: true  # Keep stdin open
    volumes:
      - ./logs:/var/log/erss